### ISSUE TITLE
aqp attempts to autoconvert SOME uuids to dates 

### ISSUE THREAD

**Issue by kirstyannepollock** [loris/api-query-params#97]
Can be tested with the following Jest test

```
const aqp = require('api-query-params')
describe('AQP test', function () {
  it('should test our aqp guid parsed as date error', done => {
    const notWorking = 'uuid=c0974f20-1071-11e7-81c3-a593aec7037f'
    const working = 'uuid=1e78b83e-d1d7-4b62-9472-d0ebf8531091'

    let aqpResult = aqp(working)
    expect(aqpResult.filter.uuid).toBe('1e78b83e-d1d7-4b62-9472-d0ebf8531091')

    aqpResult = aqp(notWorking)
    expect(aqpResult.filter.uuid).toBe('c0974f20-1071-11e7-81c3-a593aec7037f')
    done()
  })
})
```

RESULT:
```

Expected: "c0974f20-1071-11e7-81c3-a593aec7037f"
    Received: Date { NaN }

    Difference:

      Comparing two different types of values. Expected string but received date.
```
